

server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/taskmanagerservice?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: TASK-SERVICES
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka : true
    service-url:
      defaultZone: ${EUREKA_SERVER-ADDRESS:http://localhost:8761/eureka}