server:
  port: 8081

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka : true
    service-url:
      defaultZone: ${EUREKA_SERVER-ADDRESS:http://localhost:8761/eureka}
spring:
  application:
    name: API-GATEWAY
  cloud:
    discovery:
      enabled: true
